### ISSUE TITLE
deepcopy protocol 错误，请问有什么解决方法吗，谢谢

### ISSUE THREAD

**Issue by Wisdom2wisdom** [iscyy/ultralyticsPro#106]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

**_Traceback (most recent call last):
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 704, in <module>
    main(opt)
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 600, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 192, in train
    ema = ModelEMA(model) if RANK in [-1, 0] else None
  File "E:\executable_code\YOLO\yoloair2022\utils\torch_utils.py", line 307, in __init__
    self.ema = deepcopy(de_parallel(model)).eval()  # FP32 EMA_**
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\tensor.py", line 55, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

**Comment by iscyy** [comment]
Consider search engines
