### ISSUE TITLE
训练yolox-s是会出现同样的错误

### ISSUE THREAD

**Issue by tengCV** [iscyy/ultralyticsPro#12]
Traceback (most recent call last):
  File "train.py", line 690, in <module>
    main(opt)
  File "train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 253, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/home/yoloair-main/utils/autoanchor.py", line 43, in check_anchors
    anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # current anchors
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectX' object has no attribute 'anchors'

**Comment by iscyy** [comment]
you can add ` --noautoanchor`
