### ISSUE TITLE
运行ACmix报错：RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by darkredrock** [iscyy/ultralyticsPro#16]

**Comment by tengCV** [comment]
您好博主： 在使用Acmix的时候，运行到计算map时会出现一下报错（报错结果如下所示），等您有空的时候请看一下：

     Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/99     7.85G     3.891     5.434     1.282       310       640: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]                                                                 
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/41 [00:00<?, ?it/s]                                                            
Traceback (most recent call last):
  File "train.py", line 690, in <module>
    main(opt)
  File "train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 413, in train
    results, maps, _ = val.run(data_dict,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yoloair-main/val.py", line 194, in run
    outputs = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yoloair-main/models/yolo.py", line 166, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/yoloair-main/models/yolo.py", line 189, in _forward_once
    x = m(x)  # run
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yoloair-main/models/common.py", line 793, in forward
    pe = self.conv_p(position(h, w, x.is_cuda))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by iscyy** [comment]
hi, @darkredrock , @tengCV is it possible to try the following way?
Set the default parameter `half` in `val.py` to `False`

**Comment by tengCV** [comment]
好的，博主  在更换了the default parameter half in val.py to False 后依然还是会报同样的错误

**Comment by zzj9754** [comment]
@tengCV val.py的115行，half=False

**Comment by oopsboy** [comment]
> 

你好，我也遇到了同样的问题，请问你解决了吗？
