### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 1904: illegal multibyte sequence YOLO air

### ISSUE THREAD

**Issue by 4everWZ** [iscyy/ultralyticsPro#180]
我在更改YOLOv7-tiny的yaml时，选择采用其他模型yaml文件的方式，加入注意力机制，在common.py和yolo.py中都做了相应的修改。
在yolov7中可以正常运行
但是在v7-tiny中就会报错
我只是增加了个CNeB的注意力机制
具体报错信息如下：
Traceback (most recent call last):
  File "train.py", line 613, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 88, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "D:\PythonCurriculum\yoloair-yolov7-air\models\yolo.py", line 518, in __init__
    self.yaml = yaml.load(f, Loader=yaml.SafeLoader)  # model dict
  File "C:\ProgramData\anaconda3\envs\yoloair\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\ProgramData\anaconda3\envs\yoloair\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\anaconda3\envs\yoloair\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\ProgramData\anaconda3\envs\yoloair\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\ProgramData\anaconda3\envs\yoloair\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 1971: illegal multibyte sequence

**Comment by 4everWZ** [comment]
although it was in Windows11
I had already changed my system default encoding to 'utf-8'

**Comment by 4everWZ** [comment]
把yaml中的中文注释去掉就可以了
