### ISSUE TITLE
yolox:AttributeError: 'DetectX' object has no attribute 'anchors'

### ISSUE THREAD

**Issue by cfllsbb** [iscyy/ultralyticsPro#30]
I use yolox appearing the following error:
Traceback (most recent call last):
  File "train.py", line 690, in <module>
    main(opt)
  File "train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 253, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/yoloair-main/utils/autoanchor.py", line 43, in check_anchors
    anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # current anchors
  File "/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectX' object has no attribute 'anchors'

**Comment by iscyy** [comment]
you can add `--noautoanchor`

**Comment by cfllsbb** [comment]
The problem solved. Thank you!

**Comment by vaerdu** [comment]
> The problem solved. Thank you!

请问你是怎么添加的？
