### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by maoguotao-jr10** [iscyy/ultralyticsPro#38]
运行val.py时报错：
Traceback (most recent call last):
  File "D:\yoloair-main\val.py", line 399, in <module>
    main(opt)
  File "D:\yoloair-main\val.py", line 372, in main
    run(**vars(opt))
  File "D:\Python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\yoloair-main\val.py", line 204, in run
    loss += compute_loss([x.float() for x in train_out], targets)[1]  # box, obj, cls
TypeError: 'NoneType' object is not iterable

**Comment by iscyy** [comment]
update
