### ISSUE TITLE
怎么拉取最新的代码。训练yolov7-tiny 保持不了权重。

### ISSUE THREAD

**Issue by moxigk** [iscyy/ultralyticsPro#56]

**Comment by iscyy** [comment]
git related commands, Can you describe your problem more clearly?

**Comment by moxigk** [comment]
Traceback (most recent call last):
  File "train.py", line 690, in <module>
    main(opt)
  File "train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 474, in train
    results, _, _ = val.run(data_dict,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/yoloair/val.py", line 194, in run
    outputs = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/yoloair/models/yolo.py", line 197, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/root/autodl-tmp/yoloair/models/yolo.py", line 220, in _forward_once
    x = m(x)  # run
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/yoloair/models/Detect/MuitlHead.py", line 211, in fuseforward
    elif self.end2end:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'IDetect' object has no attribute 'end2end'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.


@iscyy   怎么解决呢？

**Comment by iscyy** [comment]
You can search past issues before asking: https://github.com/iscyy/yoloair/issues/22
