### ISSUE TITLE
从头训练yolox模型，报错 'DetectX' object has no attribute 'anchors'

### ISSUE THREAD

**Issue by 985zhangguoxu** [iscyy/ultralyticsPro#68]
Plotting labels to runs/train/exp4/labels.jpg... 
Traceback (most recent call last):
  File "/home/innovation/zgx/yoloair-main/train.py", line 695, in <module>
    main(opt)
  File "/home/innovation/zgx/yoloair-main/train.py", line 591, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/innovation/zgx/yoloair-main/train.py", line 254, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/home/innovation/zgx/yoloair-main/utils/autoanchor.py", line 43, in check_anchors
    anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # current anchors
  File "/home/innovation/anaconda3/envs/yoloair/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DetectX' object has no attribute 'anchors'

键入的命令是：python /home/innovation/zgx/yoloair-main/train.py --data /home/innovation/zgx/yoloair-main/data/VOC.yaml --weights '' --cfg /home/innovation/zgx/yoloair-main/configs/yolox-Improved/yolox_acmix_backbone.yaml  --img 640

请问该如何解决？谢谢

**Comment by ghost** [comment]
add --noautoanchor
