### ISSUE TITLE
从头训练yolov7-RepVGG,报错AttributeError: 'RepVGGBlock' object has no attribute 'fusevggforward'

### ISSUE THREAD

**Issue by 985zhangguoxu** [iscyy/ultralyticsPro#77]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

使用命令：python /home/innovation/zgx/yoloair-main/train.py --data /home/innovation/zgx/yoloair-main/data/VOC.yaml --weights '' --cfg /home/innovation/zgx/yoloair-main/configs/yolov7-Improved/yolov7-RepVGG.yaml --img 640

从头开始训练yolov7-RepVGG模型，训练50轮，精度为0，在使用自己训练的模型验证时，又报错：

Validating runs/train/exp29/weights/best.pt...
Fusing layers... 
Traceback (most recent call last):
  File "/home/innovation/zgx/yoloair-main/train.py", line 695, in <module>
    main(opt)
  File "/home/innovation/zgx/yoloair-main/train.py", line 591, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/innovation/zgx/yoloair-main/train.py", line 481, in train
    model=attempt_load(f, device).half(),
  File "/home/innovation/zgx/yoloair-main/models/experimental.py", line 98, in attempt_load
    model.append(ckpt.fuse().eval() if fuse else ckpt.eval())  # fused or un-fused model in eval mode
  File "/home/innovation/zgx/yoloair-main/models/yolo.py", line 309, in fuse
    m.forward = m.fusevggforward  # update forward
  File "/home/innovation/anaconda3/envs/yoloair/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'RepVGGBlock' object has no attribute 'fusevggforward'
请问作者，问题根源在哪里？如何解决？谢谢！

**Comment by iscyy** [comment]
Choose one of two options
1. Update the latest code or 2. Add switch_to_deploy function
