### ISSUE TITLE
ModuleNotFoundError: No module named 'timm'

### ISSUE THREAD

**Issue by DCH8612** [iscyy/ultralyticsPro#80]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar bug report.

### Bug

(base) ➜  yoloair git:(main) ✗ python train.py                                                      
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import val  # for end-of-epoch mAP
  File "/home/featurize/work/yoloair/val.py", line 38, in <module>
    from models.common import DetectMultiBackend
  File "/home/featurize/work/yoloair/models/common.py", line 36, in <module>
    from models.Models.muitlbackbone import conv_bn_hswish, DropPath, MobileNetV3_InvertedResidual, DepthSepConv, \
  File "/home/featurize/work/yoloair/models/Models/muitlbackbone.py", line 26, in <module>
    from models.Models.SwinTransformer import SwinTransformerLayer
  File "/home/featurize/work/yoloair/models/Models/SwinTransformer.py", line 9, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
ModuleNotFoundError: No module named 'timm'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Hyper-Devil** [comment]
pip install timm
