### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by maoguotao-jr10** [iscyy/ultralyticsPro#88]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

train.py里的workers数量默认为0，但是训练速度会很慢，当我设置为其他值的时候，第一个epoch训练完，在验证的时候遇到了如下报错。
Traceback (most recent call last):
  File "D:\yoloair-main\train.py", line 693, in <module>
    main(opt)
  File "D:\yoloair-main\train.py", line 589, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\yoloair-main\train.py", line 414, in train
    results, maps, _ = val.run(data_dict,
  File "D:\Python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\yoloair-main\val.py", line 196, in run
    out, train_out = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
ValueError: too many values to unpack (expected 2)

**Comment by iscyy** [comment]
what is the training command

**Comment by maoguotao-jr10** [comment]
已经解决，谢谢

**Comment by jayphone17** [comment]
> 已经解决，谢谢

what's the solution ?
